#!/bin/bash
# script by D3D_M4N
# this is a CIA themed hacking tool prototype
# this was designed for a linux machine with the following packages
#   nmap   w3m   git
echo "Connecting to Secure Channel...";
sleep 5
clear
echo "Connection Established!";
echo " ╔═╗  ╦  ╔═╗";
echo " ║    ║  ╠═╣";
echo " ╚═╝  ╩  ╩ ╩";
echo " Run This Program as Root";
echo "Enter Password:                                                                                 ";
read pass
if [ "$pass" = "123123qq" ]
then 
    echo Done
else
    exit
fi
clear
echo "------------------------------------------------------------------------------------------------";
echo "-                                                                                              -";
echo " ██████╗    ██╗     █████╗     ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗     ";
echo "██╔════╝    ██║    ██╔══██╗    ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║     ";
echo "██║         ██║    ███████║       ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║     ";
echo "██║         ██║    ██╔══██║       ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║     ";
echo "╚██████╗    ██║    ██║  ██║       ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗";
echo " ╚═════╝    ╚═╝    ╚═╝  ╚═╝       ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝";
echo "                                                                                                ";
echo "                                 CIA Terminal -  version 1.02                                   ";
echo "------------------------------------------------------------------------------------------------";
echo "here are your choices:";
echo " 1. Fake ID";
echo " 2. Scan an IP Address ";
echo " 3. Trace an IP Address";
echo " 4. Install Tools Needed";
read choice
if [ "$choice" = "1" ]
then 
    w3m https://www.fakenamegenerator.com/gen-male-us-us.php
fi
if [ "$choice" = "2" ]
then 
    echo Enter Target IP: && read $ip && nmap -T4 -A -v $ip
fi
if [ "$choice" = "3" ]
then 
    echo Enter Target IP: && read $ip && firefox https://tools.keycdn.com/geo?host=$ip
fi
if [ "$choice" = "4" ]
then 
    sudo bash && apt-get install w3m && apt-get install nmap 
fi